use star_line::functions::errors::CustomError;
use star_line::run;

fn main() -> Result<(), CustomError> {
    return run();
}
